DEVICE_PATH := device/xiaomi/charoite

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

# Platform
TARGET_BOARD_PLATFORM := mt6789
TARGET_BOOTLOADER_BOARD_NAME := charoite
TARGET_BOARD_SUFFIX := _64

# Kernel / DTB extracted from stock images
TARGET_NO_KERNEL := false
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
BOARD_PREBUILT_DTBIMAGE_DIR := $(DEVICE_PATH)/prebuilt
BOARD_KERNEL_IMAGE_NAME := Image
BOARD_INCLUDE_DTB_IN_BOOTIMG := false

# Boot image: stock boot.img is header v4, 64 MiB, no ramdisk
BOARD_BOOT_HEADER_VERSION := 4
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_KERNEL_PAGESIZE := 4096
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_KERNEL_CMDLINE :=

# Vendor boot: stock vendor_boot.img is header v4, 64 MiB.
# It contains 2 vendor ramdisk fragments: default + recovery.
BOARD_USES_VENDOR_BOOT := true
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOT_HEADER_VERSION := 4
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_RAMDISK_USE_LZ4 := true

# Other image sizes from stock package
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_AVB_VBMETA_IMAGE_PARTITION_SIZE := 8192
BOARD_AVB_VBMETA_SYSTEM_IMAGE_PARTITION_SIZE := 4096
BOARD_AVB_VBMETA_VENDOR_IMAGE_PARTITION_SIZE := 4096
BOARD_FLASH_BLOCK_SIZE := 131072

# A/B and dynamic partitions
AB_OTA_UPDATER := true
TARGET_OTA_ALLOW_NON_AB := false
PRODUCT_USE_DYNAMIC_PARTITIONS := true
BOARD_USES_METADATA_PARTITION := true

# Do NOT add system_dlkm here on twrp-12.1/minimal manifest:
# older TWRP build core rejects it as an invalid main partition name.
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_PARTITION_LIST := system vendor product system_ext odm vendor_dlkm odm_dlkm
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_MAIN_SIZE := 9122611200

# Filesystems
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_HAS_LARGE_FILESYSTEM := true

# Recovery / TWRP
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TW_THEME := portrait_hdpi
TW_DEFAULT_LANGUAGE := ru

TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
TW_USE_FSCRYPT_POLICY := 2

TW_INCLUDE_FASTBOOTD := true
TW_HAS_FASTBOOTD := true
TW_INCLUDE_REPACKTOOLS := true
TW_INCLUDE_RESETPROP := true
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true

TW_EXCLUDE_APEX := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_USE_TOOLBOX := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_NO_SCREEN_BLANK := true

# Build tolerance for first bring-up
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
